== 资源

我们当然已经准备好了所有的资源，万事俱备，只欠东风。 现在让我们看看怎么才能开始第一个项目，不是吗?

=== AIR SDK

如果您选择并安装了IDE，下一步是下载最新版本的AIR SDK.
Adobe每三个月发布一个新的稳定版本，所以一定要保持最新!
每个新版本通常修复了几个重要的错误，这对于保持与最新移动操作系统的兼容性尤为重要.
你也将看到其团队不断发布新的功能，而我努力让Starling跟上步伐.

最新版本可以从这里下载:
https://www.adobe.com/devnet/air/air-sdk-download.html[Download Adobe AIR SDK]

NOTE: Starling 2需要AIR 19及以上.

=== Flash Player Projector

如果你的项目打算在Flash Player中运行，我建议你下载它的独立版本，称为Projector（包含Debug和Release版本）.
Projector的优点是方便调试.
当然，你也可以通过浏览器调试（安装调试版插件后） - 但个人而言，我觉得那样非常麻烦.
独立版本播放器启动要快得多，您无需配置任何HTML文件就可以使用.

此页面包含适合开发人员的所有Flash Player版本的列表。 打开页面后查找 "projector content debugger":
https://www.adobe.com/support/flashplayer/debug_downloads.html[Adobe Flash Player Debug Downloads]

NOTE: 调试版运行速度明显比标准版本慢。 在进行性能优化时，请记住这一点.

同样，你的IDE可能需要知道如何链接到特定的播放器.
例如，在IDEA中，此设置是调试配置的一部分; 其他IDE可能只使用系统默认值.
在任何情况下，务必保证播放器版本不低于AIR SDK编译SWF时指定其运行所需的最低版本.

=== Starling

到目前为止，还需要下载的只有Starling本身了.
你有两种方式可以选择.

a. 从以下地址下载最新版本的zip文件: http://gamua.com/starling/download/[gamua.com/starling/download].
b. 克隆Starling的Git存储库.

前者的优点是它附带了一个预编译的SWC文件（位于文件夹starling / bin中），该文件很容易链接到您的项目.
但是，你使用的是本地稳定版本，这意味着你无法使用包含了新功能或修复了某些bug的热更新版本!
因此，我推荐使用Git.

TIP: 假如你报告了一个错误，这个错误在几天后被修复了（是的，确实发生过！），你必须等待我修复其它一些问题，直到我创建一个新的稳定版本，提供新的标准库swc下载，这可能需要一段时间.
但是如果你使用Git仓库，错误会立即得到修复.

深入了解Git不是本手册要讲述的内容，网上有很多关于它的教程.
安装Git后，可以使用以下命令将完整的Starling存储库下载到本地磁盘:

  git clone https://github.com/Gamua/Starling-Framework.git

Starling框架将存储在'Starling-Framework'文件夹下面.
查找实际源代码子文件夹 `starling/src`.
所有IDE都支持将此文件夹指定为项目的源路径，完成后Starling将成为目标工程的一部分.
这不会比链接到SWC文件更复杂, 并且还有另外一个好处，你可以在调试中进入Starling源代码.

这将非常容易就把Starling更新到最新版本，这是最好的办法.
只需定位到存储库的根目录并执行'pull'操作:

  cd Starling-Framework
  git pull

这比打开浏览器和手动下载新版本简单得多，不是吗?

[NOTE]
====
给高级Git用户的一些附加信息:

* Starling的所有日常开发都发生在 `master` 分支上.
* 稳定版本已独立标记（如v2.0，v2.0.1，v2.1）.
* 每个稳定版本都会打上标记并在GitHub上的发布，此时我还会附加一个预编译的SWC文件.
====

=== 获得帮助

常在江湖走，哪有不湿鞋.
你可能会因为Starling中的一个错误而碰壁 ，或者因为遇到一个似乎不可能解决的问题而困顿.
无论哪种情况，Starling社区不会让你一个人孤单寂寞冷!
此时，这里有一些资源，会对你有所帮助.

Starling 论坛::
这是Starling社区的最重要的阵地.
每天有几十个新帖子，您的问题很可能之前已被问过，所以一定要利用搜索功能寻求答案.
如果这没有帮助，请随时注册一个帐户，并发帖求助.
这会是您在网上能找到的最友好和最有耐心的社区之一! +
-> http://forum.starling-framework.org

Starling 手册::
ifdef::target-manual[您正在阅读的这本在线手册.]
ifndef::target-manual[The online manual provides an extensive introduction to Starling.]
我尽力保持与Starling新版本同步更新. +
-> http://manual.starling-framework.org

Starling Wiki::
维基包含Starling各相关主题的链接和文章，最重要的是：Starling扩展列表.
我们将在后面讨论一些. +
-> http://wiki.starling-framework.org

API 参考::
不要忘记查阅Starling API参考，了解有关所有类和方法的详细信息. +
-> http://doc.starling-framework.org

Gamua Blog::
通过Gamua博客了解Starling的最新消息.
当谈到写博客文章，我必须承认我有点懒，但每个Starling版本总是至少有一篇. +
-> http://gamua.com/blog

Twitter::
我使用了几个社交网络，最好的方式是通过@Gamua与我保持连接.
跟踪这个帐户以获得关于Starling的最新进展或链接到其他基于Starling技术创作的游戏. +
-> https://twitter.com/Gamua

