== 什么是Adobe AIR?
ifndef::imagesdir[:imagesdir: ../../img]

就在几年前，Adobe的Flash Player在web浏览器界如日中天，无处不在.
当时，如果你想创建具有互动和动画内容的网页，它基本上是唯一的选择.
浏览器在视频，声音和动画方面的能力非常有限; 并且开发者经常因为少数功能不被浏览器兼容所困扰.
总之：情况是一团糟.

这就是为什么Adobe Flash如此受欢迎的原因.
footnote:[Flash最初是由Adobe在2005年收购的Macromedia创建的。]
Adobe Flash允许设计师和开发人员在直观的创作工具（现在称为Adobe Animate）中创建多媒体内容，并确保它在所有平台上看起来一样.
Flash使用ActionScript 3编程，它是一门易于学习， 并且非常强大的编程语言.

基于其平台的普及，Adobe意识到，需要使用相同的技术,使得应用程序运行在浏览器之外.
这就是Adobe AIR运行时的目标.
使用AIR SDK构建的独立应用程序可以运行在桌面平台（Windows，macOS）或移动平台（Android，iOS）之上.
AIR的标准库是Flash的一个超集，任何你能在Flash中做到的事情，在AIR中同样可以做到；不仅如此，AIR还为文件系统访问或窗口管理等功能提供了大量额外的API.

当然，当你想创建一个桌面应用程序时，你需要一种方法来创建一个图形用户界面，对吧?
由于标准的Flash不是非常适合这个任务，所以这项任务交给了另一个SDK来承担：Flex（现在的Apache Flex）.
Flex还引入了基于XML的标记语言（称为MXML）来定义用户界面布局.

NOTE: 对于Starling，您不需要Flex SDK，只需要AIR SDK.

=== Flash和AIR的现状

AIR是"富互联网应用"（RIA）这个术语的一部分 - 这是一个流行语，在2000年末曾风行一时.
曾经，Adobe的AIR和Microsoft的Silverlight（以及Sun的JavaFX）之间存在激烈的竞争.
那么到今天，当热潮已经退去，结果又如何呢.
显然， 获胜者是HTML5 / JavaScript，它是使用Web技术构建应用程序时最受欢迎的技术.
事实上Adobe也遵循这一趋势，并且为其产品增加了越来越多的HTML5支持.

TIP: 当谈到软件开发时，不要陷入人云亦云的陷阱.
对于每个问题，会有多个解决方案; 也许其中一些不适合别人，但更适合你.
选择你最觉得最顺手的工具和方式; 让自己专注于想要创建的软件.

即使AIR / Flash可能不再是被众人所羡慕的那个"别人家的孩子", 但它仍然是一个用于构建软件非常有吸引力的平台.

* 相比HTML5的各自为政的分散现象，以及比Lady Gaga的裙子变得更快的类库来说，AIR / Flash是非常成熟和易于使用的技术平台.
* 它带有一个广泛的标准库，提供日常开发所需的所有工具.
* Flash插件虽然在一般网站上使用频率表现为衰退，但仍是网页游戏的标准. 例如，Facebook上的大多数游戏仍然使用Flash构建.
* 特别是Flash与Starling和Feathers相结合，它为真正的跨平台开发提供了最平滑的途径之一（以同一份代码为基础，可运行于所有主要桌面和移动平台）.

谈到Starling ...它是如何对应这张图片的?
